-- Users Table: Stores basic information about application users.
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Monitors Table: Defines the monitoring tasks for specific organizations.
-- - organization_name: The target company or entity to monitor.
-- - areas_of_interest: An array of keywords or topics to track (e.g., {"product launch", "customer feedback"}).
-- - schedule: A cron-formatted string defining how often to run the report (e.g., "0 9 * * 1" for 9 AM every Monday).
CREATE TABLE monitors (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    organization_name VARCHAR(255) NOT NULL,
    areas_of_interest TEXT[] NOT NULL,
    schedule VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Reports Table: Stores the output generated by the monitoring tasks.
-- - summary: The AI-generated summary of findings.
-- - sources: An array of URLs or document identifiers used to create the summary.
CREATE TABLE reports (
    id SERIAL PRIMARY KEY,
    monitor_id INTEGER NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    sources TEXT[] NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
